### PR TITLE
perf: using cheerio GrantorrentScraper instead of puppeteer

### PR DESCRIPTION
**Pull request by gecm0**
Hi @kekazoh, I noticed that you're using Puppeteer for GranTorrent instead of Cheerio. I re-implemented it with Cheerio for testing, and it works as expected. Out of curiosity, is there a specific reason you chose Puppeteer?

Feel free to close the PR if you think it is better to continue using Puppeteer in this scraper 👍🏻

### CODE REVIEW

**Comment by kekazoh** [comment]
The issue with grantorrent is that I always get this error: `SELF_SIGNED_CERT_IN_CHAIN`. Same happens when executing a simple `curl https://grantorrent.wtf` from the shell. Not sure why, but that got solved using an actual browser instead of fetch. When I try to run this branch's grantorrent scraper it raises that same error. How did you run it exactly?
Also, if we can make this work we could probably rollback the Dockerfile to a lighter image (you can see previous commits).

**Comment by gecm0** [comment]
From my local terminal `npx tsx src/scrapers/grantorrentScraper.ts`

```
Debugger attached.
{"level":"WARN","timestamp":"2024-09-26T14:42:36.159Z","logger":"kafkajs","message":"KafkaJS v2.0.0 switched default partitioner. To retain the same partitioning behavior as in previous versions, create the producer with the option \"createPartitioner: Partitioners.LegacyPartitioner\". See the migration guide at https://kafka.js.org/docs/migration-guide-v2.0.0#producer-new-default-partitioner for details. Silence this warning by setting the environment variable \"KAFKAJS_NO_PARTITIONER_WARNING=1\""}
GRANTORRENT - GETTING MOVIE LINKS https://grantorrent.wtf/buscar?q=Alicia%20en%20el%20pais%20de%20las%20maravillas
GRANTORRENT - GETTING EPISODE LINKS https://grantorrent.wtf/buscar?q=Breaking%20Bad%20-%204%C2%AA%20Temporada
GRANTORRENT - FOUND Alicia en el pais de las maravillas https://grantorrent.wtf/peliculas/8737-alicia-en-el-pais-de-las-maravillas
GRANTORRENT - CALLING getMovieInfo with https://grantorrent.wtf/peliculas/8737-alicia-en-el-pais-de-las-maravillas 2010
GRANTORRENT - FOUND TORRENT LINK /torrents/peliculas/alicia-en-el-pais-de-las-maravillas-microhd-1080-px.torrent
GRANTORRENT - FOUND FORMAT MicroHD-1080p
GRANTORRENT - FOUND YEAR 1951
GRANTORRENT - FOUND Alicia en el pais de las maravillas https://grantorrent.wtf/peliculas/6834-alicia-en-el-pais-de-las-maravillas
GRANTORRENT - CALLING getMovieInfo with https://grantorrent.wtf/peliculas/6834-alicia-en-el-pais-de-las-maravillas 2010
GRANTORRENT - FOUND Breaking Bad https://grantorrent.wtf/series/27202-breaking-bad-4a-temporada-1080p
GRANTORRENT - CALLING getEpisodeInfo with https://grantorrent.wtf/series/27202-breaking-bad-4a-temporada-1080p 4 2
GRANTORRENT - FOUND TORRENT LINK /torrents/peliculas/aliciaenelpaisdelasmaravillas.torrent
GRANTORRENT - FOUND FORMAT DVDRip
GRANTORRENT - FOUND YEAR 1951
GRANTORRENT - FOUND Alicia en el pais de las maravillas https://grantorrent.wtf/peliculas/3280-alicia-en-el-pais-de-las-maravillas
GRANTORRENT - CALLING getMovieInfo with https://grantorrent.wtf/peliculas/3280-alicia-en-el-pais-de-las-maravillas 2010
GRANTORRENT - FOUND FORMAT BluRay-1080p
GRANTORRENT - FOUND TORRENT LINK /torrents/series/Breaking_Bad_4_BluRay_Rip_1080p_01_13.torrent
GRANTORRENT - FOUND TORRENT LINK /torrents/peliculas/alicia-en-el-pais-de-dvdrip.torrent
GRANTORRENT - FOUND FORMAT DVDRip
GRANTORRENT - FOUND YEAR 2010
GRANTORRENT - FOUND Breaking Bad https://grantorrent.wtf/series/9036-breaking-bad-4a-temporada
GRANTORRENT - CALLING getEpisodeInfo with https://grantorrent.wtf/series/9036-breaking-bad-4a-temporada 4 2
MAGNETS [
  {
    magnetUrl: 'magnet:?xt=urn:btih:ced57f75d2a15d3ea61759f9c62764a228d73ebe&dn=Alicia+En+El+Pais+De+Las+Maravillas+%5BDVDRIP%5D%5BSpanish+AC3+5.1%5D%5B2010%5D',
    infoHash: 'ced57f75d2a15d3ea61759f9c62764a228d73ebe',
    size: undefined,
    files: [ [Object] ],
    quality: 'DVDRip',
    language: 'es',
    source: 'GranTorrent'
  }
]
GRANTORRENT - FOUND FORMAT HDTV
GRANTORRENT - FOUND TORRENT LINK /torrents/series/breaking-bad-4-02.torrent
MAGNETS [
  {
    magnetUrl: 'magnet:?xt=urn:btih:4cafc93d8ca6b68ccfe70bf02d44caadc6caa481&dn=Breaking+Bad+-+Temporada+4+Completa+%5BBluRay+Rip+1080p%5D%5BCap.+401_413%5D%5BAC3+5.1+Espa%C3%B1ol+Castellano-English-Subs%5D',
    infoHash: '4cafc93d8ca6b68ccfe70bf02d44caadc6caa481',
    size: undefined,
    files: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    fileIdx: 10,
    language: 'es',
    quality: 'BluRay-1080p',
    source: 'GranTorrent'
  },
  {
    magnetUrl: 'magnet:?xt=urn:btih:d18367b0369c60c739e34d062a85951d92a14b79&dn=Breaking+Bad+-+Temp.4+%5BHDTV%5D%5BCap.402%5D%5BSpanish%5D',
    infoHash: 'd18367b0369c60c739e34d062a85951d92a14b79',
    size: undefined,
    files: [ [Object] ],
    fileIdx: 0,
    language: 'es',
    quality: 'HDTV',
    source: 'GranTorrent'
  }
]
```

**Comment by kekazoh** [comment]
It seems I have some kind of network issue, maybe a softban or something like that on my local IP. I'm trying your code using a VPN and everything is running smoothly. I will do an extra commit to restore the simple node docker image and merge this pull request. Thanks for your contribution!

**Comment by kekazoh** [comment]
@patamimbre I didn't notice the pull request was pointing directly to the main branch! There shouldn't be any issue but we should take care with this. All the pull request should go to develop (unless it's a hotfix) and then we do a release from develop to main.

**Comment by gecm0** [comment]
> I didn't notice the pull request was pointing directly to the main branch! There shouldn't be any issue but we should take care with this. All the pull request should go to develop (unless it's a hotfix) and then we do a release from develop to main.


My bad, apologies! I usually point it to develop, but this time I completely missed it.

**Pull request merged**
